// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT "key", value, updated_at, created_at FROM settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingStmt, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setSetting = `-- name: SetSetting :one
INSERT INTO settings (key, value, created_at, updated_at) 
VALUES (?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET 
    value = excluded.value, 
    updated_at = excluded.updated_at
RETURNING "key", value, updated_at, created_at
`

type SetSettingParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) (Setting, error) {
	row := q.queryRow(ctx, q.setSettingStmt, setSetting,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
